### PR TITLE
Implement a following camera

### PR DESCRIPTION
**Pull request by Kaffeine**
Add a method to make the camera follow a target and use that method to follow Squad strongest machine on squad selection double-click.
To check this in game:
1. Create a Squad 1
2. Double press 1

Note: double click interval is set to 250ms (conventional value).

### CODE REVIEW

**Comment by m-flak** [comment]
Does this only toggle when you double-click the squad from the panel, or does it also toggle when you double-press the squad's selection hotkey?

**Comment by m-flak** [comment]
Just tried this out. Nice!

**Comment by Kaffeine** [comment]
Oh well, I have more commits.

https://github.com/Kaffeine/machines/commits/staging

**Comment by Kaffeine** [comment]
UX and some other changes in [staging](https://github.com/Kaffeine/machines/tree/staging):
- Lowercase `models/planet/CommSat` files (fixes crash on starting missions on the second planet on Linux)
- MachGuiCtxOptions::showDirect3DDrivers: Fix a crash on empty list
- Shortcut Shift+<0-9> to *add* selection to the squadron
- "Following camera" on double click on the machine icon
- Same-type selection by double click or click with Ctrl on the machine (in the world view)
- Same-type deselection by Ctrl+click on the icon in squadron or on a selected actor in the world view
- Removed selection clear on fast RMB click on the mini-map (felt like a bug)

I also worked on 2X UI but I had to postpone it (a lot of other refactoring needs to land first).
The next UX TODO is "Space Bar to center the screen on the location of the last event (voice mail)". Probably we'll want to filter out some event (e.g. `VID_POD_NEW_CONSTRUCTIONS` "New constructions available" but maybe more).

**Comment by Kaffeine** [comment]
image

I had to turn off asserts to do the screenshot. A lot of work ahead and the straight approach leads to a lot of issues.

**Comment by Kaffeine** [comment]
machines_1x_ui

1X UI for the contrast

**Comment by m-flak** [comment]
This is great stuff. I didn't even notice the UI was scaled up until I saw the smaller buttons. It looks good.

For screenshots, I used KDE's Spectacle from my second display. [:

**Comment by Kaffeine** [comment]
> For screenshots, I used KDE's Spectacle from my second display. [:

Oh, I use Spectacle too. I meant that with asserts turned ON the game aborts due to various `RenSurface::blit(): source area width must be less or equal to the dest area width)`. 

E.g. I increase the icon size and it tried to render outside of its parent geometry.
It happens a lot in the places where the size is taken from the bitmap and I didn't correctly apply the scale factor to the parent `Displayable`.

Do you still have interest in the development?
If yes, then maybe we can chat and discuss the project outside of GitHub PR comments?

**Comment by m-flak** [comment]
@Kaffeine Yeah, I have a renewed interest. I sent you an email. We can come up with a way to communicate.

**Pull request merged**
